// src/strings/es/common.ts
// Short words reused across screens. Area-specific text lives in its own file.

export const common = {
  close: 'Cerrar',
  cancel: 'Cancelar',
  confirm: 'Confirmar',
  back: 'Volver',
  ok: 'Aceptar',
  you: 'vos',
  host: 'Anfitrión',
  ready: 'Listo',
  actions: (n: number) => `${n} ${n === 1 ? 'acción' : 'acciones'}`,
  turn: 'Turno',
  round: 'Ronda',
  xp: 'PX',
  dangerLevel: 'Nivel de peligro',
  wounds: 'Heridas',
  backpack: 'Mochila',
  hand: 'Mano',
  inventory: 'Inventario',
  dice: 'Dados',
  damage: 'Daño',
  range: 'Alcance',
  accuracy: 'Precisión',
  noise: 'Ruido',
  dualWield: 'Ambidiestro',
  objective: 'Objetivo',
  exit: 'Salida',
  survivor: 'Superviviente',
  survivors: 'Supervivientes',
  zombie: 'Zombi',
  zombies: 'Zombis',
  zombiePhase: 'Fase de zombis',
  playerPhase: 'Fase de jugadores',
  endTurn: 'Terminar turno',
  free: 'Gratis',
  freeAction: 'Acción gratuita',
  empty: 'Vacío',
} as const;
